# NN Multiclass

In [1]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from rich import print
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
from pathlib import Path

In [2]:
def prepare_data_loaders(df, batch_size=64, test_size=0.3, random_state=42):
    """
    Prepare data loaders for training and validation
    """
    # Initialize preprocessing objects
    label_encoder = LabelEncoder()
    scaler = StandardScaler()

    # Prepare features and labels
    x_train = df.drop(['category', 'attack'], axis=1).values
    y_train = df['category']

    # Encode labels as integers
    y_train = label_encoder.fit_transform(y_train)

    # Split data
    x_train_data, x_val_data, y_train_data, y_val_data = train_test_split(
        x_train, y_train, test_size=test_size, random_state=random_state
    )

    # Scale features
    x_train_scaled = scaler.fit_transform(x_train_data)
    x_val_scaled = scaler.transform(x_val_data)

    # Convert to PyTorch tensors
    x_train_tensor = torch.tensor(x_train_scaled, dtype=torch.float32)
    x_val_tensor = torch.tensor(x_val_scaled, dtype=torch.float32)
    y_train_tensor = torch.tensor(y_train_data, dtype=torch.long)
    y_val_tensor = torch.tensor(y_val_data, dtype=torch.long)

    # Create datasets and loaders
    train_dataset = TensorDataset(x_train_tensor, y_train_tensor)
    val_dataset = TensorDataset(x_val_tensor, y_val_tensor)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

    return {
        'train_loader': train_loader,
        'val_loader': val_loader,
        'val_dataset': val_dataset,
        'input_size': x_train.shape[1],
        'num_classes': len(label_encoder.classes_),
        'class_counts': torch.bincount(y_train_tensor),
        'y_train_tensor': y_train_tensor,
        'classes': label_encoder.classes_
    }

In [3]:
class FeatureExtractor(nn.Module):
    def __init__(self, input_size):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(input_size, 512),
            nn.BatchNorm1d(512),
            nn.LeakyReLU(0.1),
            nn.Dropout(0.1)
        )

    def forward(self, x):
        return self.layers(x)

class ResidualBlock(nn.Module):
    def __init__(self, size):
        super().__init__()
        self.block = nn.Sequential(
            nn.BatchNorm1d(size),
            nn.Linear(size, 2*size),
            nn.LeakyReLU(0.1),
            nn.Linear(2*size, size),
            nn.Dropout(0.1),
        )
        self.activation = nn.LeakyReLU(0.1)

    def forward(self, x):
        identity = x
        out = self.block(x)
        out += identity
        return self.activation(out)

class NeuralNetwork(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()

        # Feature extraction path
        self.feature_extractor = FeatureExtractor(input_size)

        # Main processing path with residual connections
        self.main_path = nn.Sequential(
          ResidualBlock(512),
          ResidualBlock(512),
          ResidualBlock(512),
          nn.Linear(512, 256),
          nn.BatchNorm1d(256),
          nn.LeakyReLU(0.2),
          nn.Dropout(0.1)
        )

        self.classifier = nn.Sequential(
            nn.Linear(256, num_classes)
        )

        self._initialize_weights()

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight, mode='fan_in', nonlinearity='leaky_relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm1d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        # Extract features
        features = self.feature_extractor(x)

        # Process through main path
        main_features = self.main_path(features)

        # Classification
        output = self.classifier(main_features)

        return output

def get_optimizer(model, learning_rate=0.001, weight_decay=1e-5):
    """
    Create optimizer for the model
    """
    return torch.optim.AdamW(
        model.parameters(),
        lr=learning_rate,
        weight_decay=weight_decay,
        betas=(0.9, 0.999)
    )

def get_scheduler(optimizer):
    """
    Create learning rate scheduler
    """
    return torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode='min',
        factor=0.1,
        patience=5
    )

# Example of model initialization (to be used in the training loop):
def initialize_model(input_size, num_classes, device):
    """
    Initialize the model, optimizer, and scheduler
    """
    model = NeuralNetwork(input_size, num_classes).to(device)
    optimizer = get_optimizer(model)
    scheduler = get_scheduler(optimizer)

    return model, optimizer, scheduler

In [ ]:
def train_model(model, train_loader, val_loader, val_dataset, criterion, optimizer,
                scheduler, epochs, device, dataset_name, save_dir, goat):
    """
    Train the model and return best performance metrics
    """
    best_val_loss = float('inf')
    best_accuracy = 0.0
    patience = 10
    counter = 0

    if goat != 0:
      patience = 5

    for epoch in range(epochs):
        # Training phase
        model.train()
        epoch_loss = 0
        num_batches = len(train_loader)

        with tqdm(train_loader, desc=f"{dataset_name} - Epoch {epoch + 1}/{epochs}", bar_format='{desc}: {elapsed}') as progress_bar:
            for batch_X, batch_y in progress_bar:
                batch_X, batch_y = batch_X.to(device), batch_y.to(device)

                optimizer.zero_grad()
                outputs = model(batch_X)
                loss = criterion(outputs, batch_y)
                loss.backward()
                optimizer.step()

                epoch_loss += loss.item()
                progress_bar.set_postfix(loss=loss.item())

        # Validation phase
        model.eval()
        val_loss = 0
        correct = 0
        with torch.no_grad():
            for batch_X, batch_y in val_loader:
                batch_X, batch_y = batch_X.to(device), batch_y.to(device)
                outputs = model(batch_X)
                loss = criterion(outputs, batch_y)
                val_loss += loss.item()

                _, predicted = torch.max(outputs, 1)
                correct += (predicted == batch_y).sum().item()

        val_loss /= len(val_loader)
        accuracy = correct / len(val_dataset)

        # Learning rate scheduling
        scheduler.step(val_loss)

        # Save best model
        if accuracy > best_accuracy:
            best_accuracy = accuracy
            best_val_loss = val_loss
            save_path = Path(save_dir) / f"best_model_{dataset_name}.pth"
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'scheduler_state_dict': scheduler.state_dict(),
                'best_accuracy': best_accuracy,
                'best_val_loss': best_val_loss
            }, save_path)
            counter = 0
            
            if best_accuracy > goat:
              goat = best_accuracy
              patience = 10
        else:
            counter += 1

        print(f"{dataset_name} - Epoch {epoch + 1}/{epochs} - "
              f"Train Loss: {epoch_loss / num_batches:.4f} - "
              f"Validation Loss: {val_loss:.4f} - "
              f"Accuracy: {accuracy:.4f} - "
              f"Best Accuracy: {best_accuracy:.4f}")

        if counter >= patience:
            print(f"No improvement for {patience} epochs. Early stopping...")
            break

    return best_accuracy, best_val_loss, goat

def evaluate_model(model, val_loader, classes, device):
    """
    Evaluate the model and print classification metrics
    """
    y_pred = []
    y_true = []

    model.eval()
    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            _, predicted = torch.max(outputs, 1)
            y_pred.extend(predicted.cpu().numpy())
            y_true.extend(labels.cpu().numpy())

    y_pred = np.array(y_pred)
    y_true = np.array(y_true)

    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=classes))

    print("\nConfusion Matrix:")
    cm = confusion_matrix(y_true, y_pred)
    print(cm)

def train_on_multiple_datasets(dataset_paths, save_dir='/kaggle/working'):
    """
    Train the model sequentially on multiple datasets
    """
    # Setup device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # Create save directory
    save_dir = Path(save_dir)
    #os.makedirs("/kaggle/working/model_checkpoints", exist_ok=True)

    # Training configuration
    config = {
        'batch_size': 64,
        'epochs': 20,
        'learning_rate': 0.001,
        'weight_decay': 1e-5,
    }

    results = {}
    goat = 0.0

    # Train on each dataset sequentially
    for dataset_path in dataset_paths:
        dataset_name = Path(dataset_path).stem
        print(f"\nTraining on dataset: {dataset_name}")

        # Load and prepare data
        df = pd.read_csv(dataset_path, low_memory=False)
        data = prepare_data_loaders(df, batch_size=config['batch_size'])

        # Initialize model, optimizer, and criterion
        model = NeuralNetwork(data['input_size'], data['num_classes']).to(device)
        optimizer = get_optimizer(model, config['learning_rate'], config['weight_decay'])
        scheduler = get_scheduler(optimizer)

        # Calculate class weights for balanced training
        total_samples = len(data['y_train_tensor'])
        class_weights = total_samples / (len(data['class_counts']) * data['class_counts'])
        criterion = nn.CrossEntropyLoss(weight=class_weights.to(device))

        # Train the model
        best_accuracy, best_val_loss, goat = train_model(
            model=model,
            train_loader=data['train_loader'],
            val_loader=data['val_loader'],
            val_dataset=data['val_dataset'],
            criterion=criterion,
            optimizer=optimizer,
            scheduler=scheduler,
            epochs=config['epochs'],
            device=device,
            dataset_name=dataset_name,
            save_dir=save_dir,
            goat=goat
        )

        # Check if the best model file exists
        best_model_path = Path(save_dir) / f"best_model_{dataset_name}.pth"
        if not best_model_path.exists():
            print(f"Best model file for {dataset_name} not found. Skipping evaluation.")
            continue

        # Load best model for evaluation
        checkpoint = torch.load(best_model_path, weights_only=True)
        model.load_state_dict(checkpoint['model_state_dict'])

        # Evaluate model
        print(f"\nEvaluating model for dataset: {dataset_name}")
        evaluate_model(model, data['val_loader'], data['classes'], device)

        # Store results
        results[dataset_name] = {
            'best_accuracy': best_accuracy,
            'best_val_loss': best_val_loss
        }

    # Print final results summary
    print("\nTraining Results Summary:")
    for dataset_name, metrics in results.items():
        print(f"\n{dataset_name}:")
        print(f"Best Accuracy: {metrics['best_accuracy']:.4f}")
        print(f"Best Validation Loss: {metrics['best_val_loss']:.4f}")

In [5]:
dataset_paths = [
    "/kaggle/input/dataset/train_augmented.csv",
    "/kaggle/input/dataset/train_sel_hclust.csv",
    "/kaggle/input/dataset/merged_train.csv"
]

train_on_multiple_datasets(dataset_paths)

Using device: cuda

Training on dataset: train_augmented

train_augmented - Epoch 1/20: 00:09


train_augmented - Epoch 1/20 - Train Loss: 0.3812 - Validation Loss: 0.3542 - Accuracy: 0.7760 - Best Accuracy: 
0.7760

train_augmented - Epoch 2/20: 00:08


train_augmented - Epoch 2/20 - Train Loss: 0.3484 - Validation Loss: 0.3360 - Accuracy: 0.7962 - Best Accuracy: 
0.7962

train_augmented - Epoch 3/20: 00:08


train_augmented - Epoch 3/20 - Train Loss: 0.3348 - Validation Loss: 0.3383 - Accuracy: 0.7956 - Best Accuracy: 
0.7962

train_augmented - Epoch 4/20: 00:08


train_augmented - Epoch 4/20 - Train Loss: 0.3291 - Validation Loss: 0.3227 - Accuracy: 0.8164 - Best Accuracy: 
0.8164

train_augmented - Epoch 5/20: 00:08


train_augmented - Epoch 5/20 - Train Loss: 0.3249 - Validation Loss: 0.3363 - Accuracy: 0.8014 - Best Accuracy: 
0.8164

train_augmented - Epoch 6/20: 00:08


train_augmented - Epoch 6/20 - Train Loss: 0.3211 - Validation Loss: 0.3250 - Accuracy: 0.8177 - Best Accuracy: 
0.8177

train_augmented - Epoch 7/20: 00:09


train_augmented - Epoch 7/20 - Train Loss: 0.3186 - Validation Loss: 0.3125 - Accuracy: 0.8230 - Best Accuracy: 
0.8230

train_augmented - Epoch 8/20: 00:09


train_augmented - Epoch 8/20 - Train Loss: 0.3152 - Validation Loss: 0.3212 - Accuracy: 0.8164 - Best Accuracy: 
0.8230

train_augmented - Epoch 9/20: 00:08


train_augmented - Epoch 9/20 - Train Loss: 0.3144 - Validation Loss: 0.3160 - Accuracy: 0.8109 - Best Accuracy: 
0.8230

train_augmented - Epoch 10/20: 00:08


train_augmented - Epoch 10/20 - Train Loss: 0.3121 - Validation Loss: 0.3140 - Accuracy: 0.8203 - Best Accuracy: 
0.8230

train_augmented - Epoch 11/20: 00:09


train_augmented - Epoch 11/20 - Train Loss: 0.3092 - Validation Loss: 0.3150 - Accuracy: 0.8178 - Best Accuracy: 
0.8230

train_augmented - Epoch 12/20: 00:08


train_augmented - Epoch 12/20 - Train Loss: 0.3082 - Validation Loss: 0.3073 - Accuracy: 0.8272 - Best Accuracy: 
0.8272

train_augmented - Epoch 13/20: 00:09


train_augmented - Epoch 13/20 - Train Loss: 0.3079 - Validation Loss: 0.3314 - Accuracy: 0.8112 - Best Accuracy: 
0.8272

train_augmented - Epoch 14/20: 00:08


train_augmented - Epoch 14/20 - Train Loss: 0.3069 - Validation Loss: 0.3108 - Accuracy: 0.8222 - Best Accuracy: 
0.8272

train_augmented - Epoch 15/20: 00:08


train_augmented - Epoch 15/20 - Train Loss: 0.3061 - Validation Loss: 0.3091 - Accuracy: 0.8214 - Best Accuracy: 
0.8272

train_augmented - Epoch 16/20: 00:09


train_augmented - Epoch 16/20 - Train Loss: 0.3051 - Validation Loss: 0.3401 - Accuracy: 0.7961 - Best Accuracy: 
0.8272

train_augmented - Epoch 17/20: 00:08


train_augmented - Epoch 17/20 - Train Loss: 0.3038 - Validation Loss: 0.3070 - Accuracy: 0.8268 - Best Accuracy: 
0.8272

train_augmented - Epoch 18/20: 00:08


train_augmented - Epoch 18/20 - Train Loss: 0.3027 - Validation Loss: 0.3192 - Accuracy: 0.8232 - Best Accuracy: 
0.8272

train_augmented - Epoch 19/20: 00:09


train_augmented - Epoch 19/20 - Train Loss: 0.3025 - Validation Loss: 0.3141 - Accuracy: 0.8229 - Best Accuracy: 
0.8272

train_augmented - Epoch 20/20: 00:08


train_augmented - Epoch 20/20 - Train Loss: 0.3016 - Validation Loss: 0.3137 - Accuracy: 0.8198 - Best Accuracy: 
0.8272

/tmp/ipykernel_23/2417232063.py:177: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(best_model_path)


Evaluating model for dataset: train_augmented

Classification Report:

precision    recall  f1-score   support

        DDoS       0.69      0.64      0.66      9651
         DoS       0.66      0.71      0.68      9668
        MQTT       1.00      0.97      0.98      9502
       RECON       1.00      0.91      0.95      9700
    SPOOFING       0.81      0.99      0.89      4806

    accuracy                           0.83     43327
   macro avg       0.83      0.84      0.83     43327
weighted avg       0.83      0.83      0.83     43327

Confusion Matrix:

[[6209 3440    0    1    1]
 [2850 6818    0    0    0]
 [   0    3 9187    7  305]
 [   0    1    4 8854  841]
 [   0    1   14   17 4774]]

Training on dataset: train_sel_hclust

train_sel_hclust - Epoch 1/20: 01:16


train_sel_hclust - Epoch 1/20 - Train Loss: 0.3141 - Validation Loss: 0.3719 - Accuracy: 0.5820 - Best Accuracy: 
0.5820

train_sel_hclust - Epoch 2/20: 01:16


train_sel_hclust - Epoch 2/20 - Train Loss: 0.2871 - Validation Loss: 0.2984 - Accuracy: 0.6960 - Best Accuracy: 
0.6960

train_sel_hclust - Epoch 3/20: 01:15


train_sel_hclust - Epoch 3/20 - Train Loss: 0.2802 - Validation Loss: 0.3034 - Accuracy: 0.7173 - Best Accuracy: 
0.7173

train_sel_hclust - Epoch 4/20: 01:15


train_sel_hclust - Epoch 4/20 - Train Loss: 0.2754 - Validation Loss: 0.3109 - Accuracy: 0.7056 - Best Accuracy: 
0.7173

train_sel_hclust - Epoch 5/20: 01:16


train_sel_hclust - Epoch 5/20 - Train Loss: 0.2717 - Validation Loss: 0.3033 - Accuracy: 0.6807 - Best Accuracy: 
0.7173

train_sel_hclust - Epoch 6/20: 01:15


train_sel_hclust - Epoch 6/20 - Train Loss: 0.2696 - Validation Loss: 0.3313 - Accuracy: 0.6702 - Best Accuracy: 
0.7173

train_sel_hclust - Epoch 7/20: 01:16


train_sel_hclust - Epoch 7/20 - Train Loss: 0.2680 - Validation Loss: 0.3582 - Accuracy: 0.6001 - Best Accuracy: 
0.7173

train_sel_hclust - Epoch 8/20: 01:15


train_sel_hclust - Epoch 8/20 - Train Loss: 0.2660 - Validation Loss: 0.3758 - Accuracy: 0.6420 - Best Accuracy: 
0.7173

No improvement for 5 epochs. Early stopping...

/tmp/ipykernel_23/2417232063.py:177: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(best_model_path)


Evaluating model for dataset: train_sel_hclust

Classification Report:

precision    recall  f1-score   support

      BENIGN       1.00      1.00      1.00     57664
        DDoS       0.73      0.67      0.70    175033
         DoS       0.42      0.49      0.45     85315
        MQTT       0.99      0.96      0.98     32040
       RECON       1.00      0.90      0.95     15843
    SPOOFING       0.64      0.99      0.78      4745

    accuracy                           0.72    370640
   macro avg       0.80      0.84      0.81    370640
weighted avg       0.73      0.72      0.72    370640

Confusion Matrix:

[[ 57650      0      0      0      6      8]
 [     4 116627  58310     70      5     17]
 [     0  43548  41675     75      7     10]
 [     1      1     15  30892     10   1121]
 [    29      0      3      8  14297   1506]
 [     1      0      0     18     11   4715]]

Training on dataset: merged_train

merged_train - Epoch 1/20: 01:15


merged_train - Epoch 1/20 - Train Loss: 0.4029 - Validation Loss: 0.3825 - Accuracy: 0.7515 - Best Accuracy: 0.7515

merged_train - Epoch 2/20: 01:14


merged_train - Epoch 2/20 - Train Loss: 0.3636 - Validation Loss: 0.3610 - Accuracy: 0.7434 - Best Accuracy: 0.7515

merged_train - Epoch 3/20: 01:15


merged_train - Epoch 3/20 - Train Loss: 0.3530 - Validation Loss: 0.3637 - Accuracy: 0.7349 - Best Accuracy: 0.7515

merged_train - Epoch 4/20: 01:15


merged_train - Epoch 4/20 - Train Loss: 0.3471 - Validation Loss: 0.3704 - Accuracy: 0.7197 - Best Accuracy: 0.7515

merged_train - Epoch 5/20: 01:15


merged_train - Epoch 5/20 - Train Loss: 0.3424 - Validation Loss: 0.3639 - Accuracy: 0.7154 - Best Accuracy: 0.7515

merged_train - Epoch 6/20: 01:16


merged_train - Epoch 6/20 - Train Loss: 0.3389 - Validation Loss: 0.3396 - Accuracy: 0.7458 - Best Accuracy: 0.7515

No improvement for 5 epochs. Early stopping...

/tmp/ipykernel_23/2417232063.py:177: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(best_model_path)


Evaluating model for dataset: merged_train

Classification Report:

precision    recall  f1-score   support

      BENIGN       0.96      0.92      0.94     57664
        DDoS       0.79      0.71      0.75    175033
         DoS       0.51      0.61      0.56     85315
        MQTT       1.00      0.96      0.98     32040
       RECON       0.98      0.89      0.93     15843
    SPOOFING       0.37      0.78      0.50      4745

    accuracy                           0.75    370640
   macro avg       0.77      0.81      0.78    370640
weighted avg       0.77      0.75      0.76    370640

Confusion Matrix:

[[ 53125      0      0     11    141   4387]
 [     8 124886  50060     13      7     59]
 [     3  33110  52103     24     10     65]
 [   294      2      2  30647     66   1029]
 [   922      1      0      1  14076    843]
 [  1002      0      0      1     25   3717]]

Training Results Summary:

train_augmented:

Best Accuracy: 0.8272

Best Validation Loss: 0.3073

train_sel_hclust:

Best Accuracy: 0.7173

Best Validation Loss: 0.3034

merged_train:

Best Accuracy: 0.7515

Best Validation Loss: 0.3825